server:
  port: 0

spring:
  application:
    name: api-serie
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  zipkin:
    baseUrl: http://localhost:9411/
    enabled: true
  data:
    mongodb:
      username: usr-serie-mongo
      password: pwd-serie-mongo
      database: series-mongo
      port: 27019
      host: localhost
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

  eureka:
   healthcheck:
     enabled: true
   
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://eureka-server:8761/eureka/